name: Vinnylav
favicon: null
layout_spectrum: 0.38665
typography_spectrum: 0.15716
title: "Vinny LaVigna's Personal site"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f4f0'
    - '#292824'
    - '#913b3b'
    - '#f2bb4b'
    - '#7f7e7c'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
